### ISSUE TITLE
How to provision dashboard with own configuration files, when using dashboard image

### ISSUE THREAD

**Issue by chrisruk** [balenablocks/dashboard#31]
Hi,

I'm currently doing the following in a docker-compose file:

```
...
  dashboard:
    image: bh.cr/balenalabs/dashboard
    restart: always
    hostname: dashboard
    volumes:
        - 'dashboard-data:/data'
    ports:
        - '80'
  browser:
    image: bh.cr/balenalabs/browser-aarch64 # where <arch> is one of aarch64, arm32 or amd64
    privileged: true # required for UDEV to find plugged in peripherals such as a USB mouse
    ports:
        - '5011' # management API (optional)
        - '35173' # Chromium debugging port (optional)
    volumes:
      - 'settings:/data' # Only required if using PERSISTENT flag (see below)
    environment:
      - LAUNCH_URL=http://dashboard
...
```

I can see in the Dockerfile for  bh.cr/balenalabs/dashboard, there is the following line:
```
COPY ./provisioning /usr/share/grafana/conf/provisioning
```

I'm unsure with docker, how I specify my own yml files, when using your image, or is that not possible?

I did try cloning and modifying this repo, and referencing it from my docker-compose.yml, however I seemed to get issues -

```
[Logs]    [2023-10-05T14:51:56.378Z] [dashboard] sh: /lib/aarch64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by sh)
```

Many thanks!
